services:
  xdc-nethermind-mainnet:
    tty: true
    image: ${EC_IMAGE_VERSION}
    volumes:
    - ${EC_DATA_DIR}:/nethermind/data
    - ./start.sh:/nethermind/start.sh
    - ../bootnodes/mainnet.list:/nethermind/bootnodes.list
    entrypoint: ["bash", "/nethermind/start.sh"]
    env_file:
    - .env
    environment:
    - TERM=xterm-256color
    - COLORTERM=truecolor
    ports:
    - 30301:30301/tcp
    - 30301:30301/udp
    - ${RPC_PORT}:${RPC_PORT}
    stop_grace_period: 30s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
