services:
  releasenet1:
    container_name: xdcnetwork-releasenet-node
    image: xinfinorg/xdposchain:v2.8.2-testnet
    pull_policy: always
    volumes:
      - ./xdcchain1:/work/xdcchain
      - ./genesis.json:/work/genesis.json
      - ./bootnodes.list:/work/bootnodes.list
      - "./start-releasenet.sh:/work/start.sh"
    restart: always
    env_file:
      - releasenet1.env
    profiles:
      - machine1
    ports:
      - "8545:8545"