services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
    secrets:
      - source: users
        target: /data/users.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dozzle:/data
    ports:
      - 127.0.0.1:8080:8080
secrets:
  users:
    file: ./dozzle/users.yml
volumes:
  dozzle: