version: "3.7"

networks:
  docker_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.25.0/24

services:
  puppeth:
    image: localbuild-subnet:latest
    entrypoint: ["puppeth"]
    volumes:
      - "./puppeth:/root/.puppeth"
  bootnode:
    image: localbuild-subnet:latest
    restart: "always"
    env_file: ".env.bootnode"
    volumes:
      - "./bootnodes:/work/bootnodes"
    entrypoint: ["bash","/work/start-bootnode.sh"]
    command: ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
    ports:
      - "30301:30301/tcp"
      - "30301:30301/udp"
    networks:
      docker_net:
        ipv4_address: 
          192.168.25.10
  subnet:
    # image: xinfinorg/xdcsubnets:latest
    image: localbuild-subnet:latest
    volumes:
      - "./xdcchain:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env"
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8555:8555"
    networks:
      docker_net:
        ipv4_address: 
          192.168.25.11
  subnet2:
    # image: xinfinorg/xdcsubnets:latest
    image: localbuild-subnet:latest
    volumes:
      - "./xdcchain2:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env.2"
    ports:
      - "30304:30303"
      - "8546:8545"
      - "8556:8555"
    networks:
      docker_net:
        ipv4_address: 
          192.168.25.12
  subnet3:
    # image: xinfinorg/xdcsubnets:latest
    image: localbuild-subnet:latest
    volumes:
      - "./xdcchain3:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
    restart: "always"
    env_file: ".env.3"
    ports:
      - "30305:30303"
      - "8547:8545"
      - "8557:8555"
    networks:
      docker_net:
        ipv4_address: 
          192.168.25.13
