services:
  xinfinnetwork:
    container_name: xdcnetwork-testnet-node
    image: xinfinorg/xdposchain:v2.8.2-testnet
    volumes:
      - "./xdcchain-testnet:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
      - "./start-apothem.sh:/work/start.sh"
      - "./bootnodes.list:/work/bootnodes.list"
      - "./.pwd:/work/.pwd"
      - "/etc/localtime:/etc/localtime:ro"
    pull_policy: always
    restart: "always"
    env_file:
      - .env
    network_mode: "host"
