services:
  devnet1:
    container_name: xdcnetwork-devnet-node
    image: xinfinorg/devnet:may2026
    pull_policy: always
    volumes:
      - ./xdcchain1:/work/xdcchain
      - ./genesis.json:/work/genesis.json
      - ./bootnodes.list:/work/bootnodes.list
      - "./start-devnet.sh:/work/start.sh"
    restart: always
    env_file:
      - devnet1.env
    profiles:
      - machine1
    ports:
      - "8545:8545"