services:
  devnet1:
    image: xinfinorg/devnet:latest
    # image: xinfinorg/devnet:update-genesis-bd4cd58a5
    pull_policy: always
    volumes:
      - ./xdcchain1:/work/xdcchain
      - ./genesis.json:/work/genesis.json
      - ./bootnodes.list:/work/bootnodes.list
    restart: always
    env_file:
      - devnet1.env
    profiles:
      - machine1
    ports:
      - "8545:8545"